name: Deploy cicd-pipeline to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Test SSH Key Injection and Deploy
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          debug: true
          script_stop: true
          script: |
            echo "SSH OK"
            whoami
            hostname

            cd /home/ubuntu/cicd-pipeline
            git pull origin main

            docker stop cicd-backend || true
            docker rm cicd-backend || true

            docker build -t cicd-backend .
            docker run -d \
              --name cicd-backend \
              --restart always \
              -p 8000:8000 \
              cicd-backend
