name: Deploy cicd-pipeline to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # ðŸ” DEBUG STEP (temporary)
      - name: Debug EC2_HOST
        run: |
          echo "HOST=[$EC2_HOST]"
        env:
          EC2_HOST: ${{ secrets.EC2_HOST }}

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy to EC2
        run: |
          ssh ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
            whoami
            hostname

            cd /home/ubuntu/cicd-pipeline
            git pull origin main

            docker stop cicd-backend || true
            docker rm cicd-backend || true

            docker build -t cicd-backend .
            docker run -d \
              --name cicd-backend \
              --restart always \
              -p 8000:8000 \
              cicd-backend
          EOF
